
GET http://localhost:8080/clientes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbmlzdHJhZG9yIjp7ImlkX2FkbWluaXN0cmFkb3IiOjEsIm5vbWJyZSI6IlBhZWxzYW0iLCJjb3JyZW8iOiJwYWVsc2FtQGNvcnJlby5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCRjZXV2LkFnbWRNaTFFVzlGSVJLZS4uL1pnQm5nUDNuU3ZVaGQ2UlU4WnRwZElTNXdBWVRJSyIsImNyZWF0ZWRBdCI6IjIwMjMtMTEtMDZUMjM6NDU6MzEuNTcxWiIsInVwZGF0ZWRBdCI6IjIwMjMtMTEtMDZUMjM6NDU6MzEuNTcxWiJ9LCJpYXQiOjE3MDE5MTMyMzUsImV4cCI6MTcwMTk1NjQzNX0.c7cSnfdcPeVQ_PFGGns2D3Tqk5mBZ746dZnH_ii_q64


######

POST http://localhost:8080/clientes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbmlzdHJhZG9yIjp7ImlkX2FkbWluaXN0cmFkb3IiOjEsIm5vbWJyZSI6IlBhZWxzYW0iLCJjb3JyZW8iOiJwYWVsc2FtQGNvcnJlby5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCRjZXV2LkFnbWRNaTFFVzlGSVJLZS4uL1pnQm5nUDNuU3ZVaGQ2UlU4WnRwZElTNXdBWVRJSyIsImNyZWF0ZWRBdCI6IjIwMjMtMTEtMDZUMjM6NDU6MzEuNTcxWiIsInVwZGF0ZWRBdCI6IjIwMjMtMTEtMDZUMjM6NDU6MzEuNTcxWiJ9LCJpYXQiOjE3MDE5MTMyMzUsImV4cCI6MTcwMTk1NjQzNX0.c7cSnfdcPeVQ_PFGGns2D3Tqk5mBZ746dZnH_ii_q64


{
    "nombre": "Elkin Angulo",
    "numero_documento": "1111756702",
    "telefono": "3136961050",
    "correo": "elkin@correo.com"
}

######

PUT http://localhost:8080/clientes/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbmlzdHJhZG9yIjp7ImlkX2FkbWluaXN0cmFkb3IiOjEsIm5vbWJyZSI6IlBhZWxzYW0iLCJjb3JyZW8iOiJwYWVsc2FtQGNvcnJlby5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCRjZXV2LkFnbWRNaTFFVzlGSVJLZS4uL1pnQm5nUDNuU3ZVaGQ2UlU4WnRwZElTNXdBWVRJSyIsImNyZWF0ZWRBdCI6IjIwMjMtMTEtMDZUMjM6NDU6MzEuNTcxWiIsInVwZGF0ZWRBdCI6IjIwMjMtMTEtMDZUMjM6NDU6MzEuNTcxWiJ9LCJpYXQiOjE3MDE5MTMyMzUsImV4cCI6MTcwMTk1NjQzNX0.c7cSnfdcPeVQ_PFGGns2D3Tqk5mBZ746dZnH_ii_q64

{
    "nombre": "Samir Angulo"
}

######

DELETE http://localhost:8080/clientes/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbmlzdHJhZG9yIjp7ImlkX2FkbWluaXN0cmFkb3IiOjEsIm5vbWJyZSI6IlBhZWxzYW0iLCJjb3JyZW8iOiJwYWVsc2FtQGNvcnJlby5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCRjZXV2LkFnbWRNaTFFVzlGSVJLZS4uL1pnQm5nUDNuU3ZVaGQ2UlU4WnRwZElTNXdBWVRJSyIsImNyZWF0ZWRBdCI6IjIwMjMtMTEtMDZUMjM6NDU6MzEuNTcxWiIsInVwZGF0ZWRBdCI6IjIwMjMtMTEtMDZUMjM6NDU6MzEuNTcxWiJ9LCJpYXQiOjE3MDE5MTMyMzUsImV4cCI6MTcwMTk1NjQzNX0.c7cSnfdcPeVQ_PFGGns2D3Tqk5mBZ746dZnH_ii_q64
