
GET http://localhost:8080/empleados

######

POST http://localhost:8080/empleados
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbmlzdHJhZG9yIjp7ImlkX2FkbWluaXN0cmFkb3IiOjEsIm5vbWJyZSI6IlBhZWxzYW0iLCJjb3JyZW8iOiJwYWVsc2FtQGNvcnJlby5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCR2M09xLmhTNC5PS0tBTWFhei9xMTh1TlczRkVRV2g5ZTNvMm5DdTNhRnpQRHQ0bVJLZ2tPbSIsImNyZWF0ZWRBdCI6IjIwMjMtMTEtMDZUMTc6MDQ6NTQuODM1WiIsInVwZGF0ZWRBdCI6IjIwMjMtMTEtMDZUMTc6MDQ6NTQuODM1WiJ9LCJpYXQiOjE2OTkyOTA0OTksImV4cCI6MTY5OTM3Njg5OX0.x9NSXwSNA7YDJMoUjR7_U_Sgih09EzePGPtn0JJd0kM 

{
    "nombre": "Samir Angulo",
    "telefono": "3136961050",
    "correo": "samir@correo.com",
    "password": "Samir643"
}

######

POST http://localhost:8080/empleados/login
Content-Type: application/json

{
    "correo": "samir@correo.com",
    "password": "Samir643"
}

######

DELETE  http://localhost:8080/empleados/1