
GET http://localhost:8080/empleados

######

POST http://localhost:8080/empleados
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbmlzdHJhZG9yIjp7ImlkX2FkbWluaXN0cmFkb3IiOjEsIm5vbWJyZSI6IlBhZWxzYW0iLCJjb3JyZW8iOiJwYWVsc2FtQGNvcnJlby5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCRRYS56aGlVMFVlSHJkUC4xVmp2MmtPZGI1ei4yRHlSL20ycFZMbE96Wkw1SE9NMGdzMVI4SyIsImNyZWF0ZWRBdCI6IjIwMjMtMTItMTJUMTM6NTc6MjkuMTAxWiIsInVwZGF0ZWRBdCI6IjIwMjMtMTItMTJUMTM6NTc6MjkuMTAxWiJ9LCJpYXQiOjE3MDIzODk0NTUsImV4cCI6MTcwMjQzMjY1NX0.PjASe-M4DolqrqI0fwKpRhs6DT_Ei9Ni5OYJV6wk6HE

{
    "nombre": "Samir Angulo",
    "telefono": "3136961050",
    "correo": "samir@correo.com",
    "password": "Samir643"
}

######

POST http://localhost:8080/empleados/login
Content-Type: application/json

{
    "correo": "samir@correo.com",
    "password": "Samir643"
}

######

DELETE  http://localhost:8080/empleados/1