
GET http://localhost:8080/turnos

######

GET http://localhost:8080/turnos/cliente/1111756702

######

POST http://localhost:8080/turnos
Content-Type: application/json

{
    "id_cliente": 1,
    "id_empleado": 1,
    "id_servicio": 1
}

######

DELETE  http://localhost:8080/turnos/1